// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/const-cloudinary/analysis-go/models/components"
)

type AnalyzeCaptioningRequest struct {
	// The name of your Cloudinary cloud
	CloudName string `pathParam:"style=simple,explode=false,name=cloud_name"`
	// A JSON object containing request parameters
	BaseAnalyzeRequest components.BaseAnalyzeRequest `request:"mediaType=application/json"`
}

func (o *AnalyzeCaptioningRequest) GetCloudName() string {
	if o == nil {
		return ""
	}
	return o.CloudName
}

func (o *AnalyzeCaptioningRequest) GetBaseAnalyzeRequest() components.BaseAnalyzeRequest {
	if o == nil {
		return components.BaseAnalyzeRequest{}
	}
	return o.BaseAnalyzeRequest
}

type AnalyzeCaptioningResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Analysis succeeded
	AnalyzeCaptioningResponse *components.AnalyzeCaptioningResponse
}

func (o *AnalyzeCaptioningResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AnalyzeCaptioningResponse) GetAnalyzeCaptioningResponse() *components.AnalyzeCaptioningResponse {
	if o == nil {
		return nil
	}
	return o.AnalyzeCaptioningResponse
}
