// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/const-cloudinary/analysis-go/models/components"
)

type AnalyzeAiVisionModerationGlobals struct {
	// The name of your Cloudinary cloud
	CloudName *string `pathParam:"style=simple,explode=false,name=cloud_name"`
}

func (o *AnalyzeAiVisionModerationGlobals) GetCloudName() *string {
	if o == nil {
		return nil
	}
	return o.CloudName
}

type AnalyzeAiVisionModerationRequest struct {
	// The name of your Cloudinary cloud
	CloudName *string `pathParam:"style=simple,explode=false,name=cloud_name"`
	// A JSON object containing request parameters
	AnalyzeAIVisionModerationRequest components.AnalyzeAIVisionModerationRequest `request:"mediaType=application/json"`
}

func (o *AnalyzeAiVisionModerationRequest) GetCloudName() *string {
	if o == nil {
		return nil
	}
	return o.CloudName
}

func (o *AnalyzeAiVisionModerationRequest) GetAnalyzeAIVisionModerationRequest() components.AnalyzeAIVisionModerationRequest {
	if o == nil {
		return components.AnalyzeAIVisionModerationRequest{}
	}
	return o.AnalyzeAIVisionModerationRequest
}

type AnalyzeAiVisionModerationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Analysis succeeded
	AnalyzeAIVisionModerationResponse *components.AnalyzeAIVisionModerationResponse
}

func (o *AnalyzeAiVisionModerationResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AnalyzeAiVisionModerationResponse) GetAnalyzeAIVisionModerationResponse() *components.AnalyzeAIVisionModerationResponse {
	if o == nil {
		return nil
	}
	return o.AnalyzeAIVisionModerationResponse
}
