// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/cloudinary/analysis-go/models/components"
)

type AnalyzeUnidetRequest struct {
	// The name of your Cloudinary cloud
	CloudName string `pathParam:"style=simple,explode=false,name=cloud_name"`
	// A JSON object containing request parameters
	BaseAnalyzeRequest components.BaseAnalyzeRequest `request:"mediaType=application/json"`
}

func (o *AnalyzeUnidetRequest) GetCloudName() string {
	if o == nil {
		return ""
	}
	return o.CloudName
}

func (o *AnalyzeUnidetRequest) GetBaseAnalyzeRequest() components.BaseAnalyzeRequest {
	if o == nil {
		return components.BaseAnalyzeRequest{}
	}
	return o.BaseAnalyzeRequest
}

type AnalyzeUnidetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Analysis succeeded
	AnalyzeUnidetResponse *components.AnalyzeUnidetResponse
}

func (o *AnalyzeUnidetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AnalyzeUnidetResponse) GetAnalyzeUnidetResponse() *components.AnalyzeUnidetResponse {
	if o == nil {
		return nil
	}
	return o.AnalyzeUnidetResponse
}
