// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/const-cloudinary/analysis-go/models/components"
)

type AnalyzeGoogleTaggingGlobals struct {
	// The name of your Cloudinary cloud
	CloudName *string `pathParam:"style=simple,explode=false,name=cloud_name"`
}

func (o *AnalyzeGoogleTaggingGlobals) GetCloudName() *string {
	if o == nil {
		return nil
	}
	return o.CloudName
}

type AnalyzeGoogleTaggingRequest struct {
	// The name of your Cloudinary cloud
	CloudName *string `pathParam:"style=simple,explode=false,name=cloud_name"`
	// A JSON object containing request parameters
	BaseAnalyzeRequest components.BaseAnalyzeRequest `request:"mediaType=application/json"`
}

func (o *AnalyzeGoogleTaggingRequest) GetCloudName() *string {
	if o == nil {
		return nil
	}
	return o.CloudName
}

func (o *AnalyzeGoogleTaggingRequest) GetBaseAnalyzeRequest() components.BaseAnalyzeRequest {
	if o == nil {
		return components.BaseAnalyzeRequest{}
	}
	return o.BaseAnalyzeRequest
}

type AnalyzeGoogleTaggingResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Analysis succeeded
	AnalyzeGoogleTaggingResponse *components.AnalyzeGoogleTaggingResponse
}

func (o *AnalyzeGoogleTaggingResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AnalyzeGoogleTaggingResponse) GetAnalyzeGoogleTaggingResponse() *components.AnalyzeGoogleTaggingResponse {
	if o == nil {
		return nil
	}
	return o.AnalyzeGoogleTaggingResponse
}
