// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Responses struct {
	Value *string `json:"value,omitempty"`
}

func (o *Responses) GetValue() *string {
	if o == nil {
		return nil
	}
	return o.Value
}

type AIVisionGeneralAnalysisData struct {
	Responses    []Responses `json:"responses"`
	ModelVersion *int64      `json:"model_version,omitempty"`
}

func (o *AIVisionGeneralAnalysisData) GetResponses() []Responses {
	if o == nil {
		return []Responses{}
	}
	return o.Responses
}

func (o *AIVisionGeneralAnalysisData) GetModelVersion() *int64 {
	if o == nil {
		return nil
	}
	return o.ModelVersion
}
