// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Tags struct {
	Name *string `json:"name,omitempty"`
}

func (o *Tags) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

type AIVisionTaggingAnalysisData struct {
	Tags         []Tags `json:"tags"`
	ModelVersion *int64 `json:"model_version,omitempty"`
}

func (o *AIVisionTaggingAnalysisData) GetTags() []Tags {
	if o == nil {
		return []Tags{}
	}
	return o.Tags
}

func (o *AIVisionTaggingAnalysisData) GetModelVersion() *int64 {
	if o == nil {
		return nil
	}
	return o.ModelVersion
}
