// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AnalyzeURIRequest struct {
	// The URI of the asset to analyze
	URI *string `json:"uri,omitempty"`
	// The type of analysis to run
	AnalysisType *AnalysisType `json:"analysis_type,omitempty"`
}

func (o *AnalyzeURIRequest) GetURI() *string {
	if o == nil {
		return nil
	}
	return o.URI
}

func (o *AnalyzeURIRequest) GetAnalysisType() *AnalysisType {
	if o == nil {
		return nil
	}
	return o.AnalysisType
}
