// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AnalyzeCldTextResponseData struct {
	Entity   *string              `json:"entity,omitempty"`
	Analysis *CldTextAnalysisData `json:"analysis,omitempty"`
}

func (o *AnalyzeCldTextResponseData) GetEntity() *string {
	if o == nil {
		return nil
	}
	return o.Entity
}

func (o *AnalyzeCldTextResponseData) GetAnalysis() *CldTextAnalysisData {
	if o == nil {
		return nil
	}
	return o.Analysis
}

type AnalyzeCldTextResponse struct {
	Data      *AnalyzeCldTextResponseData `json:"data,omitempty"`
	Limits    *Limits                     `json:"limits,omitempty"`
	RequestID *string                     `json:"request_id,omitempty"`
}

func (o *AnalyzeCldTextResponse) GetData() *AnalyzeCldTextResponseData {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *AnalyzeCldTextResponse) GetLimits() *Limits {
	if o == nil {
		return nil
	}
	return o.Limits
}

func (o *AnalyzeCldTextResponse) GetRequestID() *string {
	if o == nil {
		return nil
	}
	return o.RequestID
}
