// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AnalyzeAIVisionModerationRequest struct {
	Source Source `json:"source"`
	// A list of yes/no questions
	RejectionQuestions []string `json:"rejection_questions,omitempty"`
}

func (o *AnalyzeAIVisionModerationRequest) GetSource() Source {
	if o == nil {
		return Source{}
	}
	return o.Source
}

func (o *AnalyzeAIVisionModerationRequest) GetRejectionQuestions() []string {
	if o == nil {
		return nil
	}
	return o.RejectionQuestions
}
