// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AnalyzeAIVisionGeneralRequest struct {
	Source Source `json:"source"`
	// One or more prompts of open questions or tasks with an open answer
	Prompts []string `json:"prompts,omitempty"`
}

func (o *AnalyzeAIVisionGeneralRequest) GetSource() Source {
	if o == nil {
		return Source{}
	}
	return o.Source
}

func (o *AnalyzeAIVisionGeneralRequest) GetPrompts() []string {
	if o == nil {
		return nil
	}
	return o.Prompts
}
