// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Analysis struct {
}

type AnalysisPayload struct {
	Entity   string   `json:"entity"`
	Analysis Analysis `json:"analysis"`
}

func (o *AnalysisPayload) GetEntity() string {
	if o == nil {
		return ""
	}
	return o.Entity
}

func (o *AnalysisPayload) GetAnalysis() Analysis {
	if o == nil {
		return Analysis{}
	}
	return o.Analysis
}
