// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AnalyzeCldFashionResponseData struct {
	Entity   *string                 `json:"entity,omitempty"`
	Analysis *CldFashionAnalysisData `json:"analysis,omitempty"`
}

func (o *AnalyzeCldFashionResponseData) GetEntity() *string {
	if o == nil {
		return nil
	}
	return o.Entity
}

func (o *AnalyzeCldFashionResponseData) GetAnalysis() *CldFashionAnalysisData {
	if o == nil {
		return nil
	}
	return o.Analysis
}

type AnalyzeCldFashionResponse struct {
	Data      *AnalyzeCldFashionResponseData `json:"data,omitempty"`
	Limits    *Limits                        `json:"limits,omitempty"`
	RequestID *string                        `json:"request_id,omitempty"`
}

func (o *AnalyzeCldFashionResponse) GetData() *AnalyzeCldFashionResponseData {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *AnalyzeCldFashionResponse) GetLimits() *Limits {
	if o == nil {
		return nil
	}
	return o.Limits
}

func (o *AnalyzeCldFashionResponse) GetRequestID() *string {
	if o == nil {
		return nil
	}
	return o.RequestID
}
