// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Data struct {
	Entity   *string                      `json:"entity,omitempty"`
	Analysis *AIVisionGeneralAnalysisData `json:"analysis,omitempty"`
}

func (o *Data) GetEntity() *string {
	if o == nil {
		return nil
	}
	return o.Entity
}

func (o *Data) GetAnalysis() *AIVisionGeneralAnalysisData {
	if o == nil {
		return nil
	}
	return o.Analysis
}

type AnalyzeAIVisionGeneralResponse struct {
	Data      *Data   `json:"data,omitempty"`
	Limits    *Limits `json:"limits,omitempty"`
	RequestID *string `json:"request_id,omitempty"`
}

func (o *AnalyzeAIVisionGeneralResponse) GetData() *Data {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *AnalyzeAIVisionGeneralResponse) GetLimits() *Limits {
	if o == nil {
		return nil
	}
	return o.Limits
}

func (o *AnalyzeAIVisionGeneralResponse) GetRequestID() *string {
	if o == nil {
		return nil
	}
	return o.RequestID
}
