// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TagDefinitions struct {
	// The name of the tag to apply. This can be any string and does not affect the decision process
	Name string `json:"name"`
	// A description to be used by the AI to determine whether the tag should be applied
	Description string `json:"description"`
}

func (o *TagDefinitions) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *TagDefinitions) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

type AnalyzeAIVisionTaggingRequest struct {
	Source         Source           `json:"source"`
	TagDefinitions []TagDefinitions `json:"tag_definitions"`
}

func (o *AnalyzeAIVisionTaggingRequest) GetSource() Source {
	if o == nil {
		return Source{}
	}
	return o.Source
}

func (o *AnalyzeAIVisionTaggingRequest) GetTagDefinitions() []TagDefinitions {
	if o == nil {
		return []TagDefinitions{}
	}
	return o.TagDefinitions
}
