// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AnalyzeResponse struct {
	Data      AnalysisPayload `json:"data"`
	Limits    *Limits         `json:"limits,omitempty"`
	RequestID string          `json:"request_id"`
}

func (o *AnalyzeResponse) GetData() AnalysisPayload {
	if o == nil {
		return AnalysisPayload{}
	}
	return o.Data
}

func (o *AnalyzeResponse) GetLimits() *Limits {
	if o == nil {
		return nil
	}
	return o.Limits
}

func (o *AnalyzeResponse) GetRequestID() string {
	if o == nil {
		return ""
	}
	return o.RequestID
}
