// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AnalyzeLvisResponseData struct {
	Entity   *string           `json:"entity,omitempty"`
	Analysis *LvisAnalysisData `json:"analysis,omitempty"`
}

func (o *AnalyzeLvisResponseData) GetEntity() *string {
	if o == nil {
		return nil
	}
	return o.Entity
}

func (o *AnalyzeLvisResponseData) GetAnalysis() *LvisAnalysisData {
	if o == nil {
		return nil
	}
	return o.Analysis
}

type AnalyzeLvisResponse struct {
	Data      *AnalyzeLvisResponseData `json:"data,omitempty"`
	Limits    *Limits                  `json:"limits,omitempty"`
	RequestID *string                  `json:"request_id,omitempty"`
}

func (o *AnalyzeLvisResponse) GetData() *AnalyzeLvisResponseData {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *AnalyzeLvisResponse) GetLimits() *Limits {
	if o == nil {
		return nil
	}
	return o.Limits
}

func (o *AnalyzeLvisResponse) GetRequestID() *string {
	if o == nil {
		return nil
	}
	return o.RequestID
}
