// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BaseAnalyzeRequest struct {
	Source Source `json:"source"`
}

func (o *BaseAnalyzeRequest) GetSource() Source {
	if o == nil {
		return Source{}
	}
	return o.Source
}
