// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CaptioningAnalysisDataData struct {
	Caption string `json:"caption"`
}

func (o *CaptioningAnalysisDataData) GetCaption() string {
	if o == nil {
		return ""
	}
	return o.Caption
}

type CaptioningAnalysisData struct {
	Data         CaptioningAnalysisDataData `json:"data"`
	ModelVersion *int64                     `json:"model_version,omitempty"`
}

func (o *CaptioningAnalysisData) GetData() CaptioningAnalysisDataData {
	if o == nil {
		return CaptioningAnalysisDataData{}
	}
	return o.Data
}

func (o *CaptioningAnalysisData) GetModelVersion() *int64 {
	if o == nil {
		return nil
	}
	return o.ModelVersion
}
