// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CocoAnalysisDataTags struct {
}

type CocoAnalysisData struct {
	Tags         CocoAnalysisDataTags `json:"tags"`
	ModelVersion *int64               `json:"model_version,omitempty"`
}

func (o *CocoAnalysisData) GetTags() CocoAnalysisDataTags {
	if o == nil {
		return CocoAnalysisDataTags{}
	}
	return o.Tags
}

func (o *CocoAnalysisData) GetModelVersion() *int64 {
	if o == nil {
		return nil
	}
	return o.ModelVersion
}
