// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type Feature string

const (
	FeatureGoogleTagging   Feature = "google_tagging"
	FeatureObjectDetection Feature = "object_detection"
	FeatureAiVision        Feature = "ai_vision"
)

func (e Feature) ToPointer() *Feature {
	return &e
}
func (e *Feature) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "google_tagging":
		fallthrough
	case "object_detection":
		fallthrough
	case "ai_vision":
		*e = Feature(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Feature: %v", v)
	}
}
