// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Labels struct {
	Label string  `json:"label"`
	Score float64 `json:"score"`
}

func (o *Labels) GetLabel() string {
	if o == nil {
		return ""
	}
	return o.Label
}

func (o *Labels) GetScore() float64 {
	if o == nil {
		return 0.0
	}
	return o.Score
}

type LabelAnnotations struct {
	Labels []Labels `json:"labels,omitempty"`
}

func (o *LabelAnnotations) GetLabels() []Labels {
	if o == nil {
		return nil
	}
	return o.Labels
}

type GoogleTaggingAnalysisData struct {
	LabelAnnotations LabelAnnotations `json:"label_annotations"`
}

func (o *GoogleTaggingAnalysisData) GetLabelAnnotations() LabelAnnotations {
	if o == nil {
		return LabelAnnotations{}
	}
	return o.LabelAnnotations
}
