// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type HumanAnatomyAnalysisDataTags struct {
}

type HumanAnatomyAnalysisData struct {
	Tags         HumanAnatomyAnalysisDataTags `json:"tags"`
	ModelVersion *int64                       `json:"model_version,omitempty"`
}

func (o *HumanAnatomyAnalysisData) GetTags() HumanAnatomyAnalysisDataTags {
	if o == nil {
		return HumanAnatomyAnalysisDataTags{}
	}
	return o.Tags
}

func (o *HumanAnatomyAnalysisData) GetModelVersion() *int64 {
	if o == nil {
		return nil
	}
	return o.ModelVersion
}
