// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Usage struct {
	Type  *Feature `json:"type,omitempty"`
	Count *int64   `json:"count,omitempty"`
}

func (o *Usage) GetType() *Feature {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *Usage) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

type Limits struct {
	Usage *Usage `json:"usage,omitempty"`
}

func (o *Limits) GetUsage() *Usage {
	if o == nil {
		return nil
	}
	return o.Usage
}
