// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LvisAnalysisDataTags struct {
}

type LvisAnalysisData struct {
	Tags         LvisAnalysisDataTags `json:"tags"`
	ModelVersion *int64               `json:"model_version,omitempty"`
}

func (o *LvisAnalysisData) GetTags() LvisAnalysisDataTags {
	if o == nil {
		return LvisAnalysisDataTags{}
	}
	return o.Tags
}

func (o *LvisAnalysisData) GetModelVersion() *int64 {
	if o == nil {
		return nil
	}
	return o.ModelVersion
}
