// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Security struct {
	BasicAuth *SchemeBasicAuth `security:"scheme,type=http,subtype=basic"`
	OAuth2    *string          `security:"scheme,type=oauth2,name=Authorization,env=cloudinary_o_auth2"`
}

func (o *Security) GetBasicAuth() *SchemeBasicAuth {
	if o == nil {
		return nil
	}
	return o.BasicAuth
}

func (o *Security) GetOAuth2() *string {
	if o == nil {
		return nil
	}
	return o.OAuth2
}
