// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ShopClassifierAnalysisDataTags struct {
}

type ShopClassifierAnalysisData struct {
	Tags         ShopClassifierAnalysisDataTags `json:"tags"`
	ModelVersion *int64                         `json:"model_version,omitempty"`
}

func (o *ShopClassifierAnalysisData) GetTags() ShopClassifierAnalysisDataTags {
	if o == nil {
		return ShopClassifierAnalysisDataTags{}
	}
	return o.Tags
}

func (o *ShopClassifierAnalysisData) GetModelVersion() *int64 {
	if o == nil {
		return nil
	}
	return o.ModelVersion
}
