// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UnidetAnalysisDataTags struct {
}

type UnidetAnalysisData struct {
	Tags         UnidetAnalysisDataTags `json:"tags"`
	ModelVersion *int64                 `json:"model_version,omitempty"`
}

func (o *UnidetAnalysisData) GetTags() UnidetAnalysisDataTags {
	if o == nil {
		return UnidetAnalysisDataTags{}
	}
	return o.Tags
}

func (o *UnidetAnalysisData) GetModelVersion() *int64 {
	if o == nil {
		return nil
	}
	return o.ModelVersion
}
